window.BLOOM_PRODUCTS = [
  {
    id: "bg-serum-001",
    name: "Radiance Reset Vitamin C Serum",
    category: "Skincare",
    skinType: ["Dry", "Combination", "Normal"],
    concern: ["Dullness", "Dark Spots"],
    price: 24.99,
    stock: 22,
    rating: 4.7,
    reviews: 132,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=900&q=80",
    short: "Brightening serum with stabilized vitamin C for even-toned glow.",
    ingredients: ["Vitamin C", "Ferulic Acid", "Aloe Vera"],
    crueltyFree: true,
    vegan: true
  },
  {
    id: "bg-cleanser-002",
    name: "Silk Cloud Gel Cleanser",
    category: "Skincare",
    skinType: ["Oily", "Combination", "Sensitive"],
    concern: ["Breakouts", "Texture"],
    price: 16.5,
    stock: 41,
    rating: 4.5,
    reviews: 88,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80",
    short: "Low-foam cleanser that removes impurities without stripping skin.",
    ingredients: ["Niacinamide", "Green Tea", "Panthenol"],
    crueltyFree: true,
    vegan: true
  },
  {
    id: "bg-blush-003",
    name: "Petal Flush Cream Blush",
    category: "Makeup",
    skinType: ["All"],
    concern: ["Natural Finish"],
    price: 14.25,
    stock: 17,
    rating: 4.8,
    reviews: 209,
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80",
    short: "Buildable cream blush for a soft, skin-like flush.",
    ingredients: ["Jojoba Oil", "Squalane", "Vitamin E"],
    crueltyFree: true,
    vegan: true
  },
  {
    id: "bg-lip-004",
    name: "Velvet Bloom Lip Tint",
    category: "Makeup",
    skinType: ["All"],
    concern: ["Long Wear"],
    price: 12.99,
    stock: 36,
    rating: 4.4,
    reviews: 75,
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=900&q=80",
    short: "Lightweight lip tint with lasting color and non-drying comfort.",
    ingredients: ["Hyaluronic Acid", "Shea Butter", "Peptides"],
    crueltyFree: true,
    vegan: false
  },
  {
    id: "bg-spf-005",
    name: "Daily Dew SPF 50",
    category: "Skincare",
    skinType: ["Sensitive", "Normal", "Combination"],
    concern: ["Sun Protection", "Dark Spots"],
    price: 19.75,
    stock: 0,
    rating: 4.9,
    reviews: 301,
    image: "https://images.unsplash.com/photo-1615396899839-c99c121888b0?auto=format&fit=crop&w=900&q=80",
    short: "No white cast, broad-spectrum SPF with hydrating finish.",
    ingredients: ["Zinc Oxide", "Centella", "Glycerin"],
    crueltyFree: true,
    vegan: true
  },
  {
    id: "bg-mask-006",
    name: "Overnight Repair Jelly Mask",
    category: "Skincare",
    skinType: ["Dry", "Sensitive"],
    concern: ["Barrier Repair", "Hydration"],
    price: 21,
    stock: 13,
    rating: 4.6,
    reviews: 94,
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80",
    short: "Cooling overnight mask to lock moisture and calm stressed skin.",
    ingredients: ["Ceramides", "Madecassoside", "Hyaluronic Acid"],
    crueltyFree: true,
    vegan: true
  }
];
